allow-branch = ["main"]
release = true
push = true
push-remote = "origin"
pre-release-commit-message = "(cargo-release) version {{version}}"
tag = true
tag-message = "(cargo-release) {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
publish = false
verify = true